# Generated by Django 4.0 on 2021-12-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='customURL',
            field=models.URLField(blank=True, max_length=9, null=True),
        ),
    ]
