# Generated by Django 4.0 on 2021-12-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_link_customurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='customURL',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
